import Head from "next/head";
import About from "../components/About";
import Contact from "../components/Contact";
import Favs from "../components/Favs";
import Hero from "../components/Hero";
import News from "../components/News";
import Photo from "../components/Photo";
import Testimonials from "../components/Testimonials";
import { db } from "../utils/firebase";
import { collection, query, where, getDocs, addDoc } from "firebase/firestore";
import { NextPage } from "next";
import { InferGetStaticPropsType } from "next";
import { shopProps } from "./shop";

const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  customersData,
  favItems,
}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative overflow-hidden">
        <Hero />
        <About />
        <Favs favItems={favItems} />
        <Photo />
        <Testimonials customersData={customersData} />
        <News />
        <Contact db={db} collection={collection} addDoc={addDoc} />
      </main>
    </>
  );
};

export const getStaticProps = async () => {
  const response = await fetch("https://randomuser.me/api/?results=4");
  const customersData = await response.json();

  const q = query(collection(db, "shopItems"), where("isFav", "==", true));
  const querySnapshot = await getDocs(q);

  const favItems = querySnapshot.docs.map((doc) => ({
    ...doc.data(),
    id: doc.id,
  })) as unknown as shopProps[];

  return {
    props: {
      customersData,
      favItems,
    },
    revalidate: 60,
  };
};

export default Home;
